using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Moongazing.OrionAudit.Generators;

/// <summary>
/// Emits the AOT-safe registration glue for every <c>[OrionAuditModule]</c>-decorated partial
/// class in the consuming compilation. The generator walks the same compilation for
/// <c>[Auditable]</c> types and produces, on each module:
/// <list type="bullet">
///   <item><c>RegisterAuditedTypes(AuditConfigurationBuilder)</c> — replaces the reflective scan.</item>
///   <item><c>SerializerContext</c> — static property returning a source-generated System.Text.Json context.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OrionAuditModuleGenerator : IIncrementalGenerator
{
    private const string ModuleAttributeFqn = "Moongazing.OrionAudit.OrionAuditModuleAttribute";
    private const string AuditableAttributeFqn = "Moongazing.OrionAudit.AuditableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modules = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ModuleAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol?)ctx.TargetSymbol)
            .Where(static sym => sym is not null)
            .Select(static (sym, _) => sym!)
            .Collect();

        var auditableTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AuditableAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol?)ctx.TargetSymbol)
            .Where(static sym => sym is not null
                                 && !sym.IsAbstract
                                 // The generated registration call uses the type via typeof(...) from the
                                 // emitted partial class. That requires the type to be reachable from
                                 // somewhere in the compilation — private/protected nested types
                                 // declared inside test classes etc. would not be. Skip them; the
                                 // reflective AuditConfigurationBuilder.Audit<T>() path still works for
                                 // those cases (with a trim warning).
                                 && IsReachable(sym!))
            .Select(static (sym, _) => sym!)
            .Collect();

        context.RegisterSourceOutput(modules.Combine(auditableTypes), Emit);
    }

    private static bool IsReachable(INamedTypeSymbol type)
    {
        // Walk outward through nested types — every container must be at least Internal.
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public
                && current.DeclaredAccessibility != Accessibility.Internal)
            {
                return false;
            }
        }
        return true;
    }

    private static void Emit(
        SourceProductionContext spc,
        (ImmutableArray<INamedTypeSymbol> Modules, ImmutableArray<INamedTypeSymbol> Types) input)
    {
        foreach (var module in input.Modules)
        {
            var source = EmitModule(module, input.Types);
            var hint = $"{module.ContainingNamespace.ToDisplayString().Replace('.', '_')}_{module.Name}.OrionAuditModule.g.cs";
            spc.AddSource(hint, source);
        }
    }

    private static string EmitModule(INamedTypeSymbol module, ImmutableArray<INamedTypeSymbol> types)
    {
        var ns = module.ContainingNamespace.IsGlobalNamespace
            ? null
            : module.ContainingNamespace.ToDisplayString();
        var accessibility = module.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "internal",
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Moongazing.OrionAudit;");
        sb.AppendLine("using Moongazing.OrionAudit.Configuration;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(accessibility).Append(" partial class ").AppendLine(module.Name);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers every <c>[Auditable]</c> type discovered at compile time on the supplied builder. Source-generated; no runtime reflection.</summary>");
        sb.AppendLine("    public static void RegisterAuditedTypes(AuditConfigurationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (builder is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new global::System.ArgumentNullException(nameof(builder));");
        sb.AppendLine("        }");
        foreach (var t in types)
        {
            // FullyQualifiedFormat already emits "global::Namespace.Type" — pass it straight through.
            sb.Append("        builder.Audit(typeof(")
              .Append(t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
              .AppendLine("));");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
